[package]
name = "external_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "./src/lib/lib.rs"
name = "my_lib"

[[bin]]
name = "my_bin"
path = "src/main.rs"

[dependencies]
