[package]
name = "ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.14.0"
tokio = {version =  "1.17", features = ["full"]}
reqwest = "0.11.0"
bytes = "1.3.0"
